[build]
watchPatterns = [
  "src/**/*.ts",
  "src/**/*.tsx",
  "public/**/*",
  "package.json",
  "tsconfig.json"
]

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
